twitter_faves:
  work_list:
    - dotufp
  output_bucket: dotufp-raw
  output_prefix: twitter_faves/

twitter_timeline:
  work_list:
    - dotufp

twitter_tweets:
  work_list:
    - mattyglesias

web_scrape:
  work_list:
  - politicalwire.com
