twitter_faves:
  output_bucket: dotufp-raw
  output_prefix: twitter_faves
  schedule:
    job_id: twitter-faves
    frequency: 0 */6 * * *
  work_list:
    -
      key: dotufp
      storage_key: dotufp
      twitter_id: 1198432662030970880

twitter_home_timeline:
  output_bucket: dotufp-raw
  output_prefix: twitter_home_timeline
  schedule:
    job_id: twitter-home-timeline
    frequency: 0 * * * *
  work_list:
    -
      key: dotufp
      storage_key: dotufp
      twitter_id: 1198432662030970880

twitter_timeline:
  output_bucket: dotufp-raw
  output_prefix: twitter_timeline
  schedule:
    job_id: twitter-timeline
    frequency: 0 * * * *
  work_list:
    -
      key: mattyglesias
      storage_key: mattyglesias
      twitter_id: 15446531

web_scrape:
  output_bucket: dotufp-raw
  output_prefix: web_scrape
  work_list:
    -
      key: politicalwire
      storage_key: politicalwire
      url: http://politicalwire.com
    -
      key: planets_data_eu
      storage_key: planets_data_eu
      url: http://exoplanet.eu/catalog/csv/
    -
      key: planets_data_nasa
      storage_key: planets_data_nasa
      url: http://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets&select=pl_hostname,ra,dec&order=dec
    -
      key: planets_data_oec
      storage_key: planets_data_oec
      url: https://github.com/OpenExoplanetCatalogue/oec_gzip/raw/master/systems.xml.gz
