twitter_faves:
  work_list:
    - dotufp
  output_bucket: dotufp-raw
  output_prefix: twitter_faves/

tweets_seen:
  work_list:
    - dotufp

twitter_timeline:
  work_list:
    - mattyglesias
  output_bucket: dotufp-raw
  output_prefix: twitter_timeline/

web_scrape:
  work_list:
  - politicalwire.com
