twitter_faves:
  work_list:
    - dotufp
  output_bucket: dotufp-raw
  output_prefix: twitter_faves/

twitter_home_timeline:
  work_list:
    - dotufp
  output_bucket: dotufp-raw
  output_prefix: twitter_home_timeline/

twitter_timeline:
  work_list:
    - mattyglesias
  output_bucket: dotufp-raw
  output_prefix: twitter_timeline/

web_scrape:
  work_list:
  - politicalwire.com
